---
- name: Create Top Level OU Structure
  ldap_entry:
    dn: "ou={{ item.name }},{{ item.domain_dn }}"
    objectClass: organizationalUnit
    bind_dn: "{{ dc_admin_distinguished_name }}"
    bind_pw: "{{ dc_domain_admin_password }}"
    server_uri: "ldaps:///"
  loop: "{{ dc_organizational_units }}"

- name: Create POSIX Groups
  ldap_entry:
    dn: "cn={{ item.name }},{{ item.ou_dn }}"
    objectClass: posixGroup
    bind_dn: "{{ dc_admin_distinguished_name }}"
    bind_pw: "{{ dc_domain_admin_password }}"
    server_uri: "ldaps:///"
    attributes:
      gidNumber: "{{ item.gid }}"
  loop: "{{ dc_posix_groups }}"

- name: Create POSIX Users
  ldap_entry:
    dn: "uid={{ item.username }},{{ item.ou_dn }}"
    objectClass:
      - inetOrgPerson
      - posixAccount
      - shadowAccount
    bind_dn: "{{ dc_admin_distinguished_name }}"
    bind_pw: "{{ dc_domain_admin_password }}"
    server_uri: "ldaps:///"
    attributes:
      uid: "{{ item.username }}"
      sn: "{{ item.surname }}"
      givenName: "{{ item.givenName }}"
      cn: "{{ item.username }}"
      uidNumber: "{{ item.uid }}"
      gidNumber: "{{ item.gid }}"
      userPassword: "{{ item.password }}"
      loginShell: "{{ item.shell }}"
      homeDirectory: "/home/{{ item.username }}"
  loop: "{{ dc_posix_users }}"

- name: Create InetOrgPerson Users
  ldap_entry:
    dn: "cn={{ item.username }},{{ item.ou_dn }}"
    objectClass: inetOrgPerson
    bind_dn: "{{ dc_admin_distinguished_name }}"
    bind_pw: "{{ dc_domain_admin_password }}"
    server_uri: "ldaps:///"
    attributes:
      sn: "{{ item.surname }}"
      givenName: "{{ item.givenName }}"
      cn: "{{ item.username }}"
      userPassword: "{{ item.password }}"
  loop: "{{ dc_inet_org_persons }}"

- name: Create Sudoers
  ldap_entry:
    dn: "cn={{ item.cn }},{{ item.ou_dn }}"
    objectClass:
      - top
      - sudoRole
    bind_dn: "{{ dc_admin_distinguished_name }}"
    bind_pw: "{{ dc_domain_admin_password }}"
    server_uri: "ldaps:///"
    attributes:
      cn: "{{ item.cn }}"
      sudoHost: "{{ item.sudoHost }}"
      sudoUser: "{{ item.sudoUser }}"
      sudoCommand: "{{ item.sudoCommand }}"
  loop: "{{ dc_sudoers }}"
