---
- name: create /etc/ldap/certs directory
  file:
    path: "/etc/ldap/certs/{{ dc_tld }}"
    state: directory
    mode: "u=rwx,g=rx"
  become: yes

- name: copy ldap certificate to ldap certs folder
  copy:
    src: "{{ dc_certificate_directory }}/{{ item }}"
    dest: "/etc/ldap/certs/{{ dc_tld }}/{{ item }}"
  loop:
    - "{{ dc_tls_ca_certificate_file }}"
    - "{{ dc_tls_certificate_file }}"
    - "{{ dc_tls_key_file }}"
  become: yes

- name: configure TLS in directory
  ldap_attr:
    dn: cn=config
    name: "{{ item.key }}"
    values: "{{ item.value }}"
    state: exact
  with_dict:
    olcTLSCACertificateFile: "/etc/ldap/certs/{{ dc_tld }}/{{ dc_tls_ca_certificate_file }}"
    olcTLSCertificateFile: "/etc/ldap/certs/{{ dc_tld }}/{{ dc_tls_certificate_file }}"
    olcTLSCertificateKeyFile: "/etc/ldap/certs/{{ dc_tld }}/{{ dc_tls_key_file }}"
  become: yes

- name: Set olcSecurity
  ldap_attr:
    dn: "olcDatabase={1}mdb,cn=config"
    name: olcSecurity
    values: "tls=1"
    state: present
  become: yes

- name: Enable ldaps endpoint
  lineinfile:
    path: //etc/default/slapd
    state: present
    regex: ^SLAPD_SERVICES=*
    line: 'SLAPD_SERVICES="ldap:/// ldapi:/// ldaps:///"'
  register: endpoint_status
  become: yes

- name: Restart slapd
  service:
    name: slapd
    state: restarted
  when: endpoint_status.changed
  become: yes
