---
- name: Install python-ldap
  pip:
      name: python-ldap
      state: present
  become: yes

- name: create /etc/ldap/certs directory
  file:
    path: "/etc/ldap/certs/{{ dc_tld }}"
    state: directory
    mode: "u=rwx,g=rx"
  become: yes

- name: copy ldap certificate to ldap certs folder
  copy:
    src: "{{ dc_certificate_directory }}/public/{{ item }}"
    dest: "/etc/ldap/certs/{{ dc_tld }}/{{ item }}"
  loop:
    - "{{ dc_tls_ca_certificate_file }}"
    - "{{ dc_tls_certificate_file }}"
  become: yes

- name: copy ldap certificate keys to ldap certs folder
  copy:
    src: "{{ dc_certificate_directory }}/private/{{ item }}"
    dest: "/etc/ldap/certs/{{ dc_tld }}/{{ item }}"
  loop:
    - "{{ dc_tls_key_file }}"
  become: yes

- name: write ldiff files
  template:
    src: "enable_TLS.ldif.j2"
    dest: "/etc/ldap/enable_TLS.ldif"
  become: yes

- name: enable TLS
  shell: /usr/bin/ldapmodify -Q -H ldapi:/// -Y EXTERNAL -f /etc/ldap/enable_TLS.ldif
  become: yes

- name: Set olcSecurity
  ldap_attr:
    dn: "olcDatabase={1}mdb,cn=config"
    name: olcSecurity
    values: "tls=1"
    state: exact
  become: yes

- name: Enable ldaps endpoint
  lineinfile:
    path: //etc/default/slapd
    state: present
    regex: ^SLAPD_SERVICES=*
    line: 'SLAPD_SERVICES="ldap:/// ldapi:/// ldaps:///"'
  register: endpoint_status
  become: yes

- name: Restart slapd
  service:
    name: slapd
    state: restarted
  when: endpoint_status.changed
  become: yes
