---
- name: Check if slapd service present
  service_facts:

- name: Answer slapd install questions
  debconf:
    name: slapd
    question: "{{ item.question }}"
    value: "{{ item.value }}"
    vtype: "{{ item.vtype }}"
  loop: "{{ dc_slapd_debconf }}"
  when: "'slapd' not in ansible_facts.services"

- name: Install slapd packages
  apt:
    name: "{{ dc_packages }}"
    state: present
    update_cache: yes

- name: Install python-ldap
  pip:
    name: python-ldap
    state: present

- name: Ensure slapd is started
  service:
    name: slapd
    state: started

- name: Set password for LDAP Admin User.
  ldap_passwd:
    dn: "{{ dc_admin_distinguished_name }}"
    passwd: "{{ dc_domain_admin_password }}"
    bind_dn: "{{ dc_admin_distinguished_name }}"
    bind_pw: "{{ dc_default_admin_password }}"
