---
- name: Answer slapd install questions
  debconf:
    name: slapd
    question: "{{ item.question }}"
    value: "{{ item.value }}"
    vtype: "{{ item.vtype }}"
  loop: "{{ dc_slapd_debconf }}"
  become: yes

- name: Install slapd packages
  apt:
    name: "{{ dc_packages }}"
    state: present
  become: yes
  register: install_slapd

- name: Install python-ldap
  pip:
      name: python-ldap
      state: present

- name: Set password for LDAP Admin User.
  ldap_passwd:
    dn: "{{ dc_admin_distinguished_name }}"
    passwd: "{{ dc_domain_admin_password }}"
    bind_dn: "{{ dc_admin_distinguished_name }}"
    bind_pw: "{{ dc_default_admin_password }}"
  become: yes
  when: install_slapd.changed

- name: Install sudoRole schema
  include_tasks: install_sudo_role.yml
  when: install_slapd.changed
